version: '3.7'
services:
  fun4-backend-dev:
    build: .
    environment:
      - TZ=Europe/Amsterdam
      - SPRING_PROFILES_ACTIVE=development
    image: fun4-backend-dev
    expose:
      - 4053
    container_name: fun4-backend-dev
    restart: always
    networks:
      - fun4-dev
    
networks:
  default:
    name: fun4-dev