version: '3'
services:
  fun4-backend-dev:
    build: .
    environment:
      - TZ=Europe/Amsterdam
      - SPRING_PROFILES_ACTIVE=development
    image: fun4-backend-dev
    expose:
      - 4041
    container_name: fun4-backend-dev
    restart: always