version: '3.6'
services:
  fun4-backend-dev:
    build: .
    environment:
      - TZ=Europe/Amsterdam
    image: fun4-backend-dev
    expose:
      - 4053
    container_name: fun4-backend-dev
    restart: always
    command: bash -c "cd . && java -jar -Dspring.profiles.active=development app.jar"
    networks:
      - fun4-dev

networks:
  fun4-dev:
    name: fun4-dev
    driver: bridge